// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ePEoWljmtxtTkwn6rbcZA7ncXPADRaA',
    appId: '1:1034953674987:web:7ec22eceb729e3e79faeae',
    messagingSenderId: '1034953674987',
    projectId: 'chat-app-a7b61',
    authDomain: 'chat-app-a7b61.firebaseapp.com',
    storageBucket: 'chat-app-a7b61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd_qPrHKeGWbbTV72c6-XIQCSpwjB5U80',
    appId: '1:1034953674987:android:cf3bce4cebe0d0479faeae',
    messagingSenderId: '1034953674987',
    projectId: 'chat-app-a7b61',
    storageBucket: 'chat-app-a7b61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_C6kNGrQEUWkZU1hswnfTN7v2OiPRjtk',
    appId: '1:1034953674987:ios:ac5892abe7bc47d59faeae',
    messagingSenderId: '1034953674987',
    projectId: 'chat-app-a7b61',
    storageBucket: 'chat-app-a7b61.appspot.com',
    iosBundleId: 'com.example.chachaChaudhary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_C6kNGrQEUWkZU1hswnfTN7v2OiPRjtk',
    appId: '1:1034953674987:ios:e6a90f8fff63fcc49faeae',
    messagingSenderId: '1034953674987',
    projectId: 'chat-app-a7b61',
    storageBucket: 'chat-app-a7b61.appspot.com',
    iosBundleId: 'com.example.chachaChaudhary.RunnerTests',
  );
}
